### PR TITLE
Add TPS (1m, 5m, 15m) and MSPT to ServerHealth using Paper API

### PR DESCRIPTION
**Pull request by jegt**
Uses the existing TPS data from org.bukkit.Bukkit which includes 1m, 5m and 15m (instead of just 1m) and also average MS per tick. Probably better to use the existing implementation for this than implementing it again in Lag(). I also moved these metrics to ServerHealth instead of Server.

### CODE REVIEW

**Comment by phybros** [comment]
@jegt can you add a description to the PR? What problem does this solve, why is it better than the existing `Lag()` code etc. Thank you!

**Comment by jegt** [comment]
@phybros Added a description. Hope this is clearer.

**Comment by Scarsz** [comment]
This PR would alienate any non-Paper users... hard pass from me. While Paper is certainly popular, not everyone who runs a Bukkit API-compatible server will be running a Paper one.

The old `Lag` code needs to stay in place as a fallback.

**Comment by jegt** [comment]
I can understand that you want to keep it backward compatible.  I'm not sure exactly how to make it compatible with non Paper servers since I need to specify the new Paper API in pom.xml. Its been 10+ years since I did any Java coding =)

**Comment by matteoturini** [comment]
Doesn't spigot also have a TPS API?

**Comment by jegt** [comment]
@matteoturini  No it seems to only be available for Paper.

**Comment by matteoturini** [comment]
Just looked it up, and you can use NMS and Reflection to get the TPS. Seems better than Paper API.

**Comment by jegt** [comment]
Unfortunately I don't have the time to do that. I guess I will just have to maintain this branch for my own use.

**Pull request closed without merging**
