### PR TITLE
Feature command exec

### PR DESCRIPTION
**Pull request by ATechAdventurer**
This is really a stop-gap solution until a better implementation comes along. This will only return a 200 if the command was executed, it will not return the output of the command as you might see in the console.

### CODE REVIEW

**Comment by phybros** [comment]
Looks good to me!

**Comment by Scarsz** [comment]
> return the output of the command as you might see in the console

Proper way to do that is to define a custom CommandSender that directs [`#sendMessage(...)`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/command/CommandSender.html#sendMessage(java.lang.String)) methods to the response body

[Example](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/objects/SingleCommandSender.java)

**Comment by phybros** [comment]
Is that something you can do @Scarsz ?

**Comment by Scarsz** [comment]
> Is that something you can do @Scarsz ?

Sure

**Comment by Scarsz** [comment]
https://github.com/phybros/servertap/pull/57

**Pull request merged**
