### PR TITLE
Websocket support for console (#34)

### PR DESCRIPTION
**Pull request by phybros**
DONT MERGE TILL AUTH IS FIGURED OUT.

Just wanted to push this up to get some eyeballs on it.

### CODE REVIEW

**Comment by countnoobula** [comment]
I know this is a bit out of the blue, but I want to say I really love the work you're doing!

**Comment by phybros** [comment]
Also closes #96

**Comment by phybros** [comment]
Alright. This is all done now.

This PR adds support for websockets under the path `/v1/ws/console`.

Upon connecting the last 1000 (default) lines of server console will come down the websocket connection (configurable using the `websocketConsoleBuffer ` config key.

Once connected, any server log line that goes through the normal logging filters on the server will come down the websocket in a JSON object like this:

```js
{"msg":"Done (3.412s)! For help, type \"help\"","ts":1631833562501,"l":"net.minecraft.server.MinecraftServer"}
```

Some messages will contain color codes that you will have to handle yourself:

```js
{"msg":"§6/version: §fGets the version of this server including any plugins in use","ts":1631834015918,"l":""}
```

Any message sent **up** the connection will be interpreted as a command to be executed on the server.

Since you can't set headers on websocket connections, you can't use the header `key` to authenticate like you can with regular API routes. Instead you must set a cookie called `x-servertap-key` on the page hosting the websocket connection.

Example:

```js
    // set cookie to authenticate the connection
    document.cookie = "x-servertap-key=change_me";

    this.ws = new WebSocket("ws://localhost:4567/v1/ws/console");

    this.ws.onopen = function() {
      console.log("Opened connection");
    };
```

**Comment by phybros** [comment]
OK, authentication is now on by default, and the server will yell at you if you don't change the key from the default value of `change_me`:

image

**Pull request merged**
